---
title: "About Biologized"
author: "RNPC"
date: "2022-09-23"
output: html_document
---


At Biologized, we have three goals: 

1. Make science understandable to anyone 

2. Share techniques and perspectives for students to lower the barrier of entry
of science

3. Highlight fascinating, diverse scientists to show that anyone can belong



#### *Make* complicated modern biomedical *science* *understandable* to anyone

Every year, billions of dollars are poured into scientific research in the U.S.
and across the world. The majority of this money comes from everyday people, not
unlike yourself, in the form of taxes and charitable donations (although there
is the odd billionaire who pours substantial amounts of their own money into
science). But most people have no idea what happens after that. How does money
become science and how does science return any tangible investment? We hear
about ‘investing in science’ like it is another publicly traded business but
there aren’t dependable yearly dividends when it comes to actually doing science
(trust me on that). However, biological science does have value. Substantial
value at that. We want to communicate what we know and what is new to science.
At Biologized, we translate science into something understandable to the
non-scientist and students. 



#### Share techniques and perspectives for students to *lower* *the* *barrier* of entry of science

When starting to learn science, two main themes come to the forefront of any
student: 1) rote memorization, and 2) the scientific method. I don’t believe in
rote memorization. Repeating things over and over does not help anyone learn
something. We might remember it for a bit, just long enough to get through that
next test, but in the long term, it’s not ideal. I have the memory of a hamster,
so this method of learning is a non-starter on my end. Also, google makes
memorization obsolete (there, I said it). Learning is about interacting with
material, having provoking conversations, making connections, and coming up with
new ideas. That is what we want to emphasize with this blog. As far as the
scientific method goes, critical thinking is key. Research is an intricate art.
We have to know every detail of an experiment, gently optimize the protocol, and
carefully assess the resulting data. We will provide simple explanations of some
of the most common techniques used in modern biology. Happy little mistakes
happen (sometimes not so happy). We will also give our own perspectives on the
life of a budding biomedical scientist. 


#### Highlight fascinating, diverse scientists to show that *everyone* *belongs* *in* *science*

Science happens in the context of everyday society. Be that Marie Curie’s 19th
and 20th century France or Aristotle’s Ancient Greece. There is no perfect
society and there sure as hell ain’t no perfect scientist (or writer, I might
add). Human history is riddled with mistakes, discrimination, and hidden figures
who are never recognized. This is also true for science. We hope to showcase
some of the under-appreciated scientists who have made discoveries that shape
our past, present, and future. There’s drama and despair; trials and
tribulations. Scientists are everyday people just trying to survive in the
world. Their stories are insightful, intriguing, and just plain fascinating. 

We hope you tag along and learn a thing or two about the wonders of biomedical
science and the people who make it happen. These are exciting times in biology.
Groundbreaking discoveries are happening all around us at a record pace, we just
have to take a peak. 

Nerd up and get excited about biology, folks, because it’s time to get
Biologized!
