---
title: "The Dogma"
author: "RNPC"
date: "2022-09-23"
output: html_document
---


The ‘Central Dogma’ of cell biology is the holiest of topics for a biologist, ranking up there with Natural Selection and David Attenburough narrating nature documentaries. It is the essence of molecular biology. The Central Dogma dictates: “DNA is transcribed into RNA and RNA is translated into protein” and implies that proteins then do all of the things. So what exactly does that mean? The process of transcription is the right of passage from the genetic material of DNA to the intermediate RNA (also called messenger RNA or mRNA). RNA plays the role of the messenger, carrying the word of DNA to the ribosome. At the ribosome, the Word (RNA) is read into protein and the functional worker of the cell is brought into life. 

Although these processes are, indeed, true, they are not the whole story (this is a holey topic, after all). The word dogma implies a stringent one-way process. But this is not always the case! The Central Dogma is often misrepresented in high school biology classes and even in some peer-reviewed scientific papers (we scientists are not perfect, mind you!). Although the origins of the Dogma may have been stringent when first hypothesized, modern science tells us that this is not quite a ‘set in stone’ idea; exceptions abound and are even essential for life. 

Other types of RNA can even perform tasks much like a protein. DNA itself is editable, malleable (immune system anyone?). In some cases, proteins can even be a genetic material of sorts (prions can transfer information to daughter cells). The fabled ‘Central Dogma’ of cell biology happens to be more of a ‘This is what happens most of the time’ of cell biology. This is much less catchy. It does not cleanly fit on a single powerpoint slide. Biology, as it happens, is a messy thing. But it is a mess we can make sense of.

The ‘traditional’ dogma
All that being said, we should still start with the basics then layer on the caveats from there. DNA (the genetic, inheritable material that provides the blueprints of life) is mostly useless on its own. Much like a pile of intricate drawings of a house, DNA needs to be interpreted and then structures must be made. The interpretation process is known as transcription. This is where the DNA sequence is copied and pasted into an RNA sequence. Although this sounds trivial, it is quite important. RNA can move around the cell. In the right hands, the sequence of RNA can become beautiful protein structures, elegantly designed, and performing the various tasks. 

The process of RNA being read into a protein is called translation. I think of this as the site contractor directing construction workers how to go about creating a building. In this case, every 3 bases of RNA (a codon) refers to an amino acid. As the sequence of RNA is read, more and more amino acids are strung together until a final product has been made. Oftentimes the protein still requires some other modifications but this is where the dogma ends. DNA to RNA to a protein that is free to do whatever it needs to do. Transcription followed by translation.

Well it’s a little more than that, a few examples
Now let’s add some depth to the dogma, but nothing too boat-rocking. Transcription and translation are not always occurring, they have to be controlled. Transcriptional control is one of the most tightly regulated processes in the cell. This is what ‘decides’ the fate of a gene; to live or to remain silent. Genes can be turned on or off or they can be dimmed, carefully calibrating expression to the needs of the cell. When a gene is on, the region around that sequence of DNA promotes transcription. It serves as a dock for the machinery that carries out transcription to land and get situated before starting the process of synthesizing a strand of RNA. We call this a promoter. Yet other parts of DNA can serve to enhance or suppress the transcription of a gene (I’ll let you guess what we call those -enhancers or suppressors). It’s an intricate dance to turn a gene into a molecule of RNA. There are lots of methods the cell uses to manipulate how things are transcribed within this process but we won’t be able to get into all of them here. 

Similar intricacies are true even after the molecule of RNA is transcribed. At this point, chunks of the RNA can be edited out in order to manipulate the final protein sequence (this is called alternative splicing). This allows a single gene to create multiple variations of a protein, each specialized for its own task. If a cell decides not to go through with synthesizing a protein, it can even kill that new strand of RNA, adding another layer of brakes. All the while, RNA is being coaxed from the nucleus to the ribosome, the organelle responsible for translating RNA into a chain of proteins. The processes of transcriptional and translational regulation are still not entirely clear. How does a cell know which splice of an RNA to make? What is the process of creating RNAs that end up unused? How does an RNA find the ribosome? What is the balance between promoters, enhancers, and suppressors? 

Here is where the canon ends: DNA → RNA → Protein. If breaking the rules is of interest to you, fear not. We will certainly be digging into these topics throughout the blog. More to come! Some topics that are important and break the canon (and are on the list to write about!) include: 

Reverse transcription, Retroviruses, and RNA replication
Transposons!
Prions 

So is the central dogma of cell biology wrong? Well, not exactly. It was never meant to be canon and science should always be challenged. Nothing is ever absolute in biology.


