---
title: "Selecting a TAC"
author: "RNPC"
date: "2022-10-02"
categories: ["advisory", "committee", ]
page-layout: "article"
---

I'm selecting my Thesis Advisory Committee at the moment. To be quite honest, I
never really thought about this part of the PhD journey. It crept up on me and I
now have a week to assemble the group of people who will evaluate my work for
the next 4+ years. These are the folks who will decide when (or if) I can
graduate with a PhD. Needless to say this is more important than I realized and
I do regret not giving it a bit more thought prior to the week before I have to
turn in the names. So, what is the Thesis Advisory Committee (TAC)? What will
they do? How do I choose?

A Thesis Advisory Committee is typically a group of scientists who follow your
progress through the PhD program. Sometimes called a Dissertation Advisory
Committee (or just advisory committee) these are the people who decide my fate
as a PhD student. I will meet with them every six months until they decide that
I am ready to defend my thesis work (and escape graduate school in a reasonable
amount of time). Although the details vary by program, my TAC will be chaired by
my Thesis Advisor (the person whose lab I joined for my work), two faculty at my
graduate school, and one faculty from another graduate program. At each meeting
I will present my most recent data (if any), they will (grill me) offer advice
for a couple of hours, and I will try not to feel dismayed. At least this is how
I expect them to go. I can give an update later on. In general, it's a way to
hold grad students accountable and push them forward, especially when their work
is hitting obstacles or stagnating. For my program, I have to select these
members, ask them to take time out of their very busy schedules, and hope I made
the right decision.

Selecting TAC members seemed like an easy thing to do at first. I was planning
on just finding faculty who would be "yes people" and let me graduate as quickly
as possible. But a PhD is based on thought and rationale and that seems like the
least thoughtful way to pick mentors. So I've gone back to the drawing board...
I asked for advice from the administrative assistant for the department, Amy.
She helped me come up with a short list that I could work with, and I finally
selected one of my committee members thanks to her input. This particular
person, Scott, is known as a very clever experimental designer. He could be
valuable to have around in the so-called 'doldrums of third year', a time
notorious for experiments failing and prospects turning bleak. One down, two to
go.

Considering my thesis work is on retrotransposons, I decided my other TAC
members should have some expertise in the field. I met a high-profile scientist
at my first conference in Ireland named Kathy. She's an MD/PhD and basically
runs the cancer retrotransposon field. I had a great chat with her concerning my
work and she offered to be on the committee at the time, with one caveat: make
sure that my project will actually have something to do with this topic. Kathy,
after all, is a busy person. So I spent my summer validating my ideas and
providing 'proof of concept' data. Once I had a few solid pieces of evidence she
agreed. Two down, one to go.

The last member of my TAC is maybe a bit more of a stretch. He works outside of
my department (epigenetics) as a structural biologist. My work (almost
certainly) will have no structural components to it. However, he is an internal
faculty member and has a project a bit related to my proposal. He is also a
young faculty member who just started his lab within the last year or so. It
would be nice to have a perspective of someone who has experienced graduate
school a little more recently than the rest. He should have some empathy along
with his scientific expertise. A win-win if you ask me. Three members down.

I had success recruiting all three simply by cold email. They were all eager to
help. But why? Why should these prominent scientists work with yet another
student? Oftentimes it is a requirement as a professor (simple enough) but I
reckon there are at least two other reasons for them to participate in these
committees. First, each time they mentor a student to a successful PhD, they can
add that to their own resume. It's a big deal to get a PhD, but it's an even
bigger deal to help many students get PhDs. Demonstrating a commitment to
expanding science is an important part of being a scientific leader.

Second, they can spread their philosophies of science to a greater audience than
the confines of their lab members. Although I imagine this may not be a
conscious decision for them, I think that an important part of a TAC is simply
learning how to do and think about science. This is heavily influenced by the
folks who mentor you. Your TAC mentors you. This provides them an opportunity to
imprint thinking not just within their own field but in disparate disciplines
that may only be tangentially related. Again, this last point is my opinion so
make of it what you wish.

With my TAC assembled, I will schedule my first meeting with them in a couple of
months. But when I say schedule, I mean Amy, the admin assistant, will schedule.
She's the glue that keeps this whole shenanigan together. At that first meeting,
I'll present my proposed thesis and they will rip it apart and challenge me to
think even deeper. Totally expected but will still be painful. Wish. Me. Luck.

Some advice for picking TAC members:

1\. Don't pick a yes-person. This is the group of people who will push your
science to the next level. Complacency is not an option. Having someone who will
quietly sit back while you talk and ask minimal questions does not help your
science or your career. You want people who will challenge you and make you
think critically. After all, that's what science is about.

2\. Diversify your investments. This finance advice applies readily to picking a
TAC member. Having multiple people on a committee who think the same way and ask
the same questions does not broaden your perspective as a scientist. Make sure
your TAC members represent different areas in which you want to improve. You
will have plenty of time throughout graduate school to make the connections you
need. These are the folks who will help get you there.

3\. Plan farther ahead than I did. My TAC selection strategy was non-existent
until I was reminded that I only have a few more days to pick committee members.
I don't recommend this. Plan ahead. Talk to potential members well in advance.
People like to know what is coming up and would almost always prefer a heads up
email to a 'hey I need to make a TAC right now, are you in? Let me know in the
next hour." This is a poor strategy to get things from other people in any
situation, especially in science.
