---
title: "The Hallmarks of Cancer"
author: "RNPC"
date: "2022-10-02"
categories: ["cancer","disease", "proliferation", "angiogenesis","apoptosis","replication","metastisis"]
page-layout: "article"
---

So let’s start with what I consider the brass tacks of modern cancer biology: a
now iconic review article by Douglas Hanahan and Robert Weinberg titled ‘The
Hallmarks of Cancer’. We’ll use this paper as a jumping off point to understand
modern cancer biology. Published at the turn of the millenia, this review
presents the culmination of cancer research in the 20th century. It unifies the
field by providing a structure to think about the way cancer grows, survives,
and progresses. Prior to this article, the field of cancer research, having
produced enormous amounts of new information, had not yet come to a consensus of
what unifies the class of diseases called cancer. What do they all have in
common?

These authors proposed (and many agree) that every cancer has some combination
of 6 acquired capabilities that the rest of our cells do not have. For each of
these topics, entire books could be written about what scientists have
discovered. But here, I just want to present the concept behind the science.
Hopefully it gets your wheels spinning and your innovative, problem-solving
juices flowing. ‘The Hallmarks of Cancer’ is now a foundational article in the
cancer field, shaping and directing research throughout the 21st century. (For
those who are into binging, there are two sequels that we’ll discuss in other
posts!)

I use the analogy of a criminal organization to represent cancer throughout
this post. This will help us skirt around the details of which mechanisms
drive specific characteristics and stay big-picture. In fact, I have
intentionally left out as much jargon as possible for a reason; I find that
the weeds of protein names and scientific language often get in the way of the
actual science (the exciting part). We are here to understand the forest, not
the individual trees; the interesting science, not the excruciating details.
There will be plenty of that in other posts. 

**Self-Sufficiency in Growth Signals** Cancer is a disease of growth. Cells
divide, then divide again... And again. On and on this cycle goes until a
patient is treated or passes away. Now, normally, cells do not divide on their
own. They need input and encouragement from other cells and parts of the body
before they begin division. Dividing takes a LOT of energy and is dangerous when
out of control. So a single cell does not divide without being told to do so. 

As you could guess, this is not the case with cancer cells. Cancer cells find
ways to avoid needing growth signals in the first place. Cancer cells do this
in a few ways, such as making their own growth signals or rewiring how they
respond to other cells. Think of it like making their own black market money.
Cancer cells print their own money (i.e. make more growth signals) or rewire
their bank account to artificially add a few more zeros to the end of their
growth signaling balance. 

**Insensitivity to anti-growth signals** As much as cancer cells can print their
own growth signaling money and divide at will, tissues have other ways to make
sure this doesn’t get out of control. Cells in a tissue are not only deprived
given the signal to divide, they are intentionally given signals NOT to divide.
This adds another layer of protection against over-proliferation in tissue. I
think of this as ignoring the rules when it comes to money. If the rules of a
tissue say ‘Don’t divide’, then you probably shouldn’t divide. Cancer, of
course, ignores the rules. When anti growth signals are around and the law is
set, they still divide (those hooligans!). 

**Tissue invasion and metastasis** An important and deadly feature of cancer is
that it can move to different parts of the body. This is typically a ‘bad sign’
when it comes to patient survival. Most of the time, the original clump of
cancer cells (known as the primary tumor) are not directly the cause of death.
Usually, new tumors (from the same original population of cancer cells) begin to
appear in distant parts of the body. This is especially bad when they get into
the brain and lungs, where just the presence of extra cells can impair function. 

In many ways this is like a criminal organization setting up a branch in a
new country. It is a difficult task to get out of the original country,
travel across a long distance, and set up shop somewhere completely foriegn.
Each type of cell is made to live and function in a very specific
environment in a given tissue. But a few successful cancer cells (and
criminal organizations) can grow into a new land. The new growth is referred
to as a metastasis (‘met’ for short). It means that the cancer cells have
adapted to new environments. The criminal organization is getting bigger and
becoming more dangerous.

**Limitless replicative potential** It may come as a bit of a surprise to find
out that cells throughout the human body have a built-in timer. They can divide
a certain number of times, then they become stuck and unable to divide any
further. Of course this would be a problem for a cancerous enterprise intent on
dividing indefinitely. Cancer cells must develop a way to avoid the limitations
of their internal clock. 

It’s a lot like a criminal organization making long term plans. They have to
have a hierarchy and a plan for the next generation in order to survive for a
prolonged period of time. The same is true for cancer cells, if they are
relegated to only a certain number of divisions, they likely will not make
enough cells with enough new mutations to progress into more dangerous stages
of cancer. 

**Sustained angiogenesis** It takes a lot of raw materials to run any
organization, including the criminal sort. Infrastructure has to be in place in
order for operations to run smoothly. A tumor is no exception. As cancer cells
grow and divide, the innermost part of the tumor becomes isolated from the
nutrient rich blood vessels near the tumor surface. Over time, this creates
pressure for the cancer cells to develop new ways of getting nutrients. They
accomplish this in a process called ‘angiogenesis’. 

The word angiogenesis consists of two Greek root words: angio (meaning
“vessel”) and genesis (meaning “to be born”). In the human body angio refers
to the vessels that transport substances around tissues. Our blood vessels are
the main highways by which nutrients are delivered to tissues. Lots of blood
vessels means plenty of nutrients like oxygen, sugar, and signaling molecules
can access a tissue. In order to get the supplies needed for constant
division, cancer cells can secrete signals that tell new blood vessels to
start growing into the tumor. The blood vessels themselves are not cancerous,
they are just responding to signaling molecules made by cancer cells. This
results in tumors that are chalked full of blood vessels, like highways
delivering goods directly to the criminal’s layer.

**Evading apoptosis** For each of the hallmarks we’ve touched on, there are fail
safes, backups, and redundancies that usually help cells avoid being part of the
problem that is cancer. Healthy cells can sense when the hallmarks of cancer are
being activated and remove itself from the equation in a mechanism called
apoptosis. This is a mechanism of self sacrifice that can be activated in a cell
in MANY ways including, but not limited to: resistance to growth signaling,
insensitivity to antigrowth signals, and changing replicative potential. These
are some of the key hallmarks of any cancer! So, in order for a cancer cell to
acquire ANY ONE of those characteristics, it has to escape detection and
destruction by apoptosis. 

Apoptosis is the law enforcement mechanism of the cell. If things are going
wrong (way wrong) the cell is destroyed and its contents recycled back into
the surrounding tissue. Cancers would be very unlikely to arise if they did
not find methods to avoid the apoptosis coppers. Although it’s a simple
sounding concept (just don’t die, right?), cells are tenaciously caught
between easily programmed death and signaling that keeps them alive. It is not
difficult to alert the cops to cellular wrongdoing. Cells can very easily
apoptose (I have killed many cells in the lab by accident). Surveillance is in
every nook and cranny of the cell, ready to activate apoptosis quickly and
completely. Once apoptosis begins, it cannot stop. But cancer cells don’t let
apoptosis begin.

As I round out this post, I should note that I have admittedly
anthropomorphized a lot of details in cancer to fit the ‘criminal
organization’ analogy. Although it can be a pet peeve of mine when this
happens in a scientific meeting or paper, I think it is a fine tool to convey
foundational concepts in biology. However, cancer cells do not plan; they do
not think ahead; they do not coordinate an attack with other cancer cells
across the body. They are bound to chance mutations in order to gain these
capabilities. There are means by which odds can increase or decrease depending
on many factors, but at the end of the day, cells are at the mercy of
mutations.

There are many thihngs that I didn't touch on in this post. I did that on
purpose (HA!). Like I said earlier, the main concept, the “forest”, is what is
most important. The cellular mechanisms that make these hallmarks so important
are complicated and can cloud the big picture. BUT, they are not impossible to
understand. If you are asking yourself “How does a cell recruit a blood vessel?”
or “What is the process of moving a cancer cell to a new tissue” then you are
thinking like a scientist and you are on your way to understanding already!
These are some of the MANY active areas of cancer research happening in labs
around the world right now. We will certainly cover some of these in the future.
Some of the proteins and mechanisms that help cancer cells perform the hallmarks
are well-known. But others are still quite mysterious…
